### ISSUE TITLE
Diversity shulker dupe

### ISSUE THREAD

**Issue by angrykoteuko** [FaeWulf/Diversity#1]
If option "bundle_place_mode" is false in diversity.json config, shulker boxes will dupes in survival mode on fabric server

**Comment by FaeWulf** [comment]
Can you describe more specific?

**Comment by FaeWulf** [comment]
Nvm thank you very much!

**Comment by angrykoteuko** [comment]
When the option is turned off, when placing the shulker box, it is installed, but does not disappear from the hand

**Comment by FaeWulf** [comment]
version 1.1.1 will fix this issue! I will try to push it as soon as possible!

**Comment by angrykoteuko** [comment]
thanks!
