### ISSUE TITLE
[BUG/CRASH] Bone mealing coral fans causes a server crash

### ISSUE THREAD

**Issue by chi-bat** [FaeWulf/Diversity#11]
Tested with 1.3.4 for 1.21, bone mealing any types of coral fans will cause a server crash, here is an associated crash report

[crash-2024-08-21_21.19.34-server.txt](https://github.com/user-attachments/files/16698861/crash-2024-08-21_21.19.34-server.txt)

**Comment by FaeWulf** [comment]
Hard conflict with "carpet" mod, which also has the coral bonemeal feature. I will update the mod asap!

**Comment by FaeWulf** [comment]
This feature will be disabled (forced, can't be turned on) if there is carpet mod, you will want to enable carpet mod's gamerule: renewableCoral

Issue fixed in latest version, sorry for the late!
https://modrinth.com/mod/faewufs-diversity/versions
