### ISSUE TITLE
"baby" nametag is invalid

### ISSUE THREAD

**Issue by specialTT** [FaeWulf/Diversity#12]
I used this feature in 1.21 but it had no effect.

**Comment by specialTT** [comment]
> 我在1.21中使用過這個功能，但沒有效果。

**Comment by FaeWulf** [comment]
Umm, can I get the reason why it did not work? Just curious

**Comment by specialTT** [comment]
I don't know, but I added this mod to my own mod pack. I suspect it is a module conflict problem. Here is the link to all the mod files in my mod pack: https://docs.google.com/document/d/1Qd8kZvSkfpfqH0ayDoHdwGfHdAUM-2f6DrM4aQ3YILs/edit?usp=sharing(I am Taiwanese, the content is in Chinese, but there is an English module name), there are too many mods, and it may not be possible to find the problem. By the way, does the nametag text work case-insensitively?

**Comment by FaeWulf** [comment]
It isn't case insensitively, bbut to be sure, use the latest versioin

**Comment by specialTT** [comment]
I just re-tested and found that the "baby" nametag does not prevent the baby from growing up, but it can prevent the baby from being fed to speed up its growth.

**Comment by FaeWulf** [comment]
Alright I will fix this asap

**Comment by specialTT** [comment]
Did you encounter it during testing? If it's a problem with my own mod pack, I don't need to trouble you, because it's outside your jurisdiction and I should figure it out myself.

**Comment by FaeWulf** [comment]
> Did you encounter it during testing? If it's a problem with my own mod pack, I don't need to trouble you, because it's outside your jurisdiction and I should figure it out myself.

I found the issue (it's my mod issue), I will update the mod as soon as possible! Don't worry about it!

**Comment by specialTT** [comment]
Thanks!

**Comment by FaeWulf** [comment]
Updated the mod, sorry for the late!
https://modrinth.com/mod/faewufs-diversity/versions
