### ISSUE TITLE
[BUG] Game Crashing in Modpack

### ISSUE THREAD

**Issue by 612aidan** [FaeWulf/Diversity#15]
### Describe the bug
When I try to run this mod with my modpack, it crashes the whole game and doesn't open at all.

### To Reproduce
Steps to reproduce the behavior: Try to load game with my modpack. There's around 200 mods in here and I have no idea which ones are causing the issues. I would list the mods but it's probably easier to just look through the crash report

### Expected behavior
I expect the game to load.

### Additional info
- Game version: 1.21
- Mod version: 2.0.0
- Mod list: (optional)

### Crash log/ Gamelog
[crash-2024-09-07_15.20.52-client.txt](https://github.com/user-attachments/files/16919695/crash-2024-09-07_15.20.52-client.txt)

**Comment by FaeWulf** [comment]
Hard conflict with "Easy Shulkerboxes". I will fix this issue asap.

**Comment by FaeWulf** [comment]
Fixed att 2.0.1, test it!
https://modrinth.com/mod/faewufs-diversity/versions

**Comment by 612aidan** [comment]
My game did not crash this time! Thanks for the update!
