### ISSUE TITLE
[Suggestion] Add a block tag listing exceptions for the "Bonemeal small flowers" feature.

### ISSUE THREAD

**Issue by ExDrill** [FaeWulf/Diversity#18]
### Is your feature request related to a problem? Please describe.
Yes, from a technical and compatibility standpoint, adding exceptions to the "Bonemeal small flowers" feature is difficult.

### Describe the solution you'd like
Instead of manually checking for a Torchflower and Wither Rose, utilize another block tag, this will open up many opportunities for modpack creators and other mod developers.

**Comment by FaeWulf** [comment]
Ok I will try to add compatibility for thiis.
#small_flower_bonemealable to make it bonemealable
I don't know I should add another tag for the blacklist

**Comment by FaeWulf** [comment]
Added in v.2.1.0, you can check the Change log for more detail :) tysm.
https://modrinth.com/mod/faewufs-diversity/versions
