### ISSUE TITLE
[BUG] Console spam with stdout reset:0

### ISSUE THREAD

**Issue by payphone101** [FaeWulf/Diversity#19]
### Describe the bug
Mod spams the console with stdout reset 0 (I figured this out using another mod called BadStdOut)

### To Reproduce
1. Install Diversity
2. Set config for reverse phantom spawing to`false`
3. Check console

### Expected behavior
No console spam

### Screenshots
![image](https://github.com/user-attachments/assets/a68386ce-0c00-4918-a5db-6e8f1807890c)

### Additional info
- Game version: FABRIC 1.21.1
- Mod version: `v.1.21-2.1.0`
- Mod list: (optional)

### Crash log/ Gamelog
(optional)

**Comment by FaeWulf** [comment]
Ohh... I forgot to remove the debug message, my bad :/
Will be fixed in the nexxt version

**Comment by FaeWulf** [comment]
Fixed in the latest version https://modrinth.com/mod/faewufs-diversity/versions
Sorry for the late update.
