### ISSUE TITLE
[FEATURE] Please can you add a config for Eggs?

### ISSUE THREAD

**Issue by makumaku1974** [FaeWulf/Diversity#2]
The problem with too many chickens in my world causes insane lag spikes. Instead of them spawning anywhere please whitelist it only for haybales so it doesnt cause frame issues. Thank you.

**Comment by FaeWulf** [comment]
Sure! I will make them only try hatch in haybale only in the next update! might take 1-2 days.

**Comment by makumaku1974** [comment]
> Sure! I will make them only try hatch in haybale only in the next update! might take 1-2 days.

Thank you. Now it wont cheese the game or even mess with the fps yet still quite the harvest too.
![Screenshot 2024-06-28 221630](https://github.com/FaeWulf/Diversity/assets/129804277/c0973d02-614e-464f-9fd8-6efc82254cd8)

**Comment by FaeWulf** [comment]
Solved in latest version! https://modrinth.com/mod/faewufs-diversity/version/1.2.0+1.21
