### ISSUE TITLE
Breaks the datapack works

### ISSUE THREAD

**Issue by angrykoteuko** [FaeWulf/Diversity#3]
Mod will cause bug with KawaMood's Waystones - they look like a barrels, not waystones
![image](https://github.com/FaeWulf/Diversity/assets/165277433/eb30b86f-1756-4b94-8b8e-fb6839026b52)
After deleting Diversity from mods and replace waystone blocks they looks right
![image](https://github.com/FaeWulf/Diversity/assets/165277433/bc56848a-2fdd-4565-93e1-a5838fa3f03b)

**Comment by FaeWulf** [comment]
Thank you very much! This issue will be fixed in the next update, will take around 1 day!

**Comment by FaeWulf** [comment]
solved in latest version!
https://modrinth.com/mod/faewufs-diversity/version/1.2.0+1.21
