### ISSUE TITLE
Bundle enchantment bugged?

### ISSUE THREAD

**Issue by SS4BLADE** [FaeWulf/Diversity#5]
i enchanted my bundle with capacity 3 and it still only lets me add 64 items :(

https://github.com/user-attachments/assets/7b31e5bb-b4d8-4507-aa62-e1f5893cf543

**Comment by FaeWulf** [comment]
Can I get the list of mods your installed? Also the diversity's current setting if you can.

**Comment by SS4BLADE** [comment]
![image_2024-08-06_161103771](https://github.com/user-attachments/assets/0fa7e3e4-071c-4027-a6b3-4a399a714528)
![image_2024-08-06_161133638](https://github.com/user-attachments/assets/685bc78a-89b0-4dd3-876d-bc61efe9eb02)


let me know if you need more?

**Comment by FaeWulf** [comment]
Diversity is currently imcompatible with "Easy Shulkker Boxes". I will fix this problems asap

**Comment by SS4BLADE** [comment]
Okay no worries thankyou so much!! any chance i can get a reply on this thread when the update is released if you remember :)

**Comment by FaeWulf** [comment]
Updated to mod! 
https://modrinth.com/mod/faewufs-diversity/version/1.3.2+1.21
Can you try again if it works? 
Thank you for the report!

**Comment by SS4BLADE** [comment]
Sorry for the late reply i have tested it all again and it works fine now thankyou sm <3
