### ISSUE TITLE
Polydex and PolydexBridge support

### ISSUE THREAD

**Issue by noiverre** [FaeWulf/Diversity#6]
is it possible to include support for Polydex and PolydexBridge for craftable items, so that they will show up in EMI client-side without installing the mod?

**Comment by FaeWulf** [comment]
Hmm, which mean you want all custom recipe to show up in JEI right? If that, I will try to do it!

**Comment by noiverre** [comment]
> Hmm, which mean you want all custom recipe to show up in JEI right? If that, I will try to do it!

for PolydexBridge it specifically only support EMI, JEI and REI is more widely used but EMI having zero external dependency makes it the best choice for a "modded vanilla" server

https://modrinth.com/mod/polydex-bridge

**Comment by FaeWulf** [comment]
I have tested it (Diiversity installed servers-side, vanilla client/EMI) recipe for sus sand/gravel shows up as exxpected. Only bundle's recipe doesn't show up in the search tab, because it locked it client-side. I will try to find a way to do this. thank you!

**Comment by noiverre** [comment]
Yeah I was having issues with Diversity Bundle standalone where the recipe don't work on client-side only, the report issue on Modrinth leads here so I thought every craftable in Diversity was basically the same, now TIL that bundle recipes are client hardlocked so I guess there's no workaround, thanks anyway!

**Comment by FaeWulf** [comment]
Updated for better bundle: https://modrinth.com/mod/diversity-better-bundle/versions
Main mod will update later. Thank you for the report!

**Comment by kawazoe** [comment]
It looks like the recent versions of the mod have a regression and this fix doesn't work anymore.

v2.5.0 for 1.20.1 doesn't show the recipe in JEI or the vanilla recipe book. The feature declaration appear to be missing from the pack.mcmeta in the latest branch.

**Comment by FaeWulf** [comment]
Check version 2.5.1, it should work now for 1.20.1.
