### ISSUE TITLE
[BUG] Crashing with Divergent Progression

### ISSUE THREAD

**Issue by makumaku1974** [FaeWulf/Diversity#9]
Durability that replaces the tool with DP mod crashes with your mod.

![image](https://github.com/user-attachments/assets/7077f467-6173-4aaf-8f5e-e4290d52b16b)

**Comment by makumaku1974** [comment]
https://github.com/BlueStaggo/divergent-progression/issues/4#issuecomment-2286623853

**Comment by FaeWulf** [comment]
I will look into the problem, thank you for the report!

**Comment by FaeWulf** [comment]
Btw, can you tell me the way to reproduce this bug?

**Comment by FaeWulf** [comment]
I found the root of this problem! Unfortunatly, this is a problem with a library I am using, so I will report this problem to it, sorry I can't do anything further.

**Comment by FaeWulf** [comment]
Updated version 1.3.4 fixed the issue for me, please try it out! Thank you for the report.
https://modrinth.com/mod/faewufs-diversity/version/1.3.4+1.21

**Comment by makumaku1974** [comment]
Love the mod and will try this out now.
